development:
  adapter: postgresql
  host: localhost
  database: asm_development
  pool: 16
  timeout: 5000
  username: <%= ENV['DB_USER'] || 'vagrant' %>

test:
  adapter: postgresql
  host: localhost
  database: asm_test
  pool: 16
  timeout: 5000
  username: <%= ENV['DB_USER'] || 'vagrant' %>
